# Generated by Django 5.1.4 on 2024-12-19 18:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('city_address', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('opening_hours', ckeditor.fields.RichTextField()),
                ('facebook_link', models.CharField(max_length=50)),
                ('instagram_link', models.CharField(max_length=50)),
                ('x_link', models.CharField(max_length=50)),
                ('linkedin_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort', 'name'), 'verbose_name_plural': 'Categories'},
        ),
    ]
