# Generated by Django 5.1.4 on 2024-12-19 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactinfo_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?(380)?\\d{9,15}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
